bucket_name  = "chainlink-storage-bucket"
cluster_name = "cluster"
clusters     = "[map[cluster_location:us-central1 master_ipv4_cidr_block:192.168.2.1/24 secondary_range_pods:pods secondary_range_services:services subnetwork:un-central1]]"
network      = "test"
project_id   = "sapient-helix-352609"
